### ISSUE TITLE
Cookie values not updating on server

### ISSUE THREAD

**Issue by biofractal** [VeliovGroup/Meteor-Cookies#1]
I am finding that updated cookies values are not being picked up server-side. Here is my code.

**Client**

```
Tracker.autorun ->
    userId = Meteor.userId()
    loginToken = localStorage.getItem "Meteor.loginToken"
    if userId? and loginToken?
        Meteor.cookie.set "meteor_user_id", userId
        Meteor.cookie.set "meteor_token", loginToken
    else
        Meteor.cookie.remove "meteor_user_id"
        Meteor.cookie.remove "meteor_token"
```

This works fine. As I sign in and sign out the cookie values are created and removed correctly.

**Server**

```
getUserFromCookie=(request)->
    return unless Meteor.cookie.has('meteor_user_id') and Meteor.cookie.has('meteor_token')
    Meteor.users.findOne 
        _id: Meteor.cookie.get 'meteor_user_id'
        'services.resume.loginTokens.hashedToken' : Accounts._hashLoginToken Meteor.cookie.get 'meteor_token'

Router.route '/test/user',
    name : 'user'
    where: 'server'
    action: ->
        user = getUserFromCookie @request
        console.log user
        @response.end()
```

The server route will only ever see the first values set. Upadting the values on the client has no effect.

Thanks

**Comment by dr-dimitru** [comment]
Hi @biofractal , from the docs:

> Note: On server, cookies will be set only after headers is sent (on next route or page reload)
1. Are you sure you refresh user's page (to send cookies to server)?
2. Make sure cookies in domain wide, from docs:

> if path not specified, defaults to the current path of the current document location

**Comment by dr-dimitru** [comment]
@biofractal any news on your end?

**Comment by biofractal** [comment]
Hi

Sorry for the delay - I asked my question then went away on holiday :-) After a bit of experimentation I am still struggling to get this working. 
1. _Are you sure you refresh user's page (to send cookies to server)?_
   The reason I am using the package is to secure an api endpoint that is acting as a callback location. My app redirects to a third party that does some processing and then posts back to my api end-point. I want to set a temporary cookie so that the posted callback can be authenticated as being initiated from the current browser. The problem is that the cookie is not set, perhaps because the redirects do not count as a page refresh as far as meteor is concerned.
2. _Make sure cookies in domain wide, from docs:_
   I am currently testing locally so setting the domain to `null` seems to be setting the domain to `localhost` (using chrome), which is what I want I believe

**Comment by dr-dimitru** [comment]
Hi, I'm working around cookies v2.0.0 (new API). All current issues will be fixed. I'll update you after publishing new package

**Comment by dr-dimitru** [comment]
Could you please update and test your app with [`v2.0.0-beta`](https://github.com/VeliovGroup/Meteor-Cookies/releases/tag/v2.0.0-beta)
Added `apply()` client's method to send cookies to server

**Comment by biofractal** [comment]
The new features look like they are just what I need but has the `v2.0.0-beta` package been published? I am still getting `version 1.0.1` when I add via `meteor add`

**Comment by dr-dimitru** [comment]
Yes it is published, but as it is beta, you need to run exactly: 

``` shell
meteor add ostrio:cookies@2.0.0-beta
```

**Comment by dr-dimitru** [comment]
BTW to see all published package versions:

``` shell
meteor show --show-all ostrio:cookies
```

**Comment by dr-dimitru** [comment]
New version is available: 

``` shell
meteor add ostrio:cookies@2.0.0-beta.1
```

**Comment by biofractal** [comment]
Thanks for the advice. I will go get it installed now.

**Comment by dr-dimitru** [comment]
@biofractal Let me know if everything is going well with updated driver, so I'll publish stable release

**Comment by dr-dimitru** [comment]
@biofractal tested and published as v2.0.0

**Comment by biofractal** [comment]
That all worked a treat. Thanks for your efforts getting this package done and thanks for helping me out. 

Just in case it is useful to anybody else; here is the working code (coffeescript) I ended up with. If you spot any cookie usage errors here then please shout out.

### Client

```
Tracker.autorun ->
    userId = Meteor.userId()
    loginToken = localStorage.getItem "Meteor.loginToken"
    if userId? and loginToken?
        cookies.set "meteor_user_id", userId
        cookies.set "meteor_token", loginToken
    else
        cookies.remove "meteor_user_id"
        cookies.remove "meteor_token"
    cookies.send()
```

### Client / Server

```
@cookies = new Cookies()

getUserFromCookie=(req)->
    cookies = req.Cookies
    userId = cookies.get 'meteor_user_id'
    token = cookies.get 'meteor_token'
    return unless userId? and token?
    Meteor.users.findOne 
        _id: userId
        'services.resume.loginTokens.hashedToken' : Accounts._hashLoginToken(token)

Router.route '/pdf/:id',
    name : 'generatePDF'
    where: 'server'
    action: ->
        user = getUserFromCookie @request
        unless user?
            @response.statusCode = 403;
            return @response.end 'not allowed'

        # carry on with generating the PDF ...
```

**Comment by roblingle** [comment]
I'm using @biofractal's example code above except plain JS, and leaving out the `@cookies` bit in my routes file.

The problem I'm running into is that `this.request.Cookies` is not defined in my router action. 
Any thoughts on why that might happen?

I also tried just using `cookies = new Cookies()`, but then `cookies.keys()` is an empty array. I can see that they are set on the client, and I have called `cookies.send()`

**Comment by dr-dimitru** [comment]
Hi @roblingle ,
Which version of driver and Meteor you are using?
Have you tried [alternate usage](https://github.com/VeliovGroup/Meteor-Cookies#alternate-usage) example, attaching cookies controller via middleware?

``` javascript
/* Server */
if(Meteor.isServer){
  var cookie = new Cookies({
    auto: false, // Do not bind middleware by default
    handler: function(cookies){
      // Here you can use `cookies` argument
    }
  });

  WebApp.connectHandlers.use(cookie.middleware());
}
```

**Comment by roblingle** [comment]
I'm using Meteor 1.2.1 and version 2.0.1 of this package.

The alternate usage doesn't seem to do anything when I put it it in my router action:

``` javascript
Router.route('/users/export', {
  name:   'admin.users.export',
  where:  'server',
  action() {
    // let user = getUserFromCookie(this.request);
    let keys;
    var cookie = new Cookies({
      auto: false, // Do not bind middleware by default
      handler: function(cookies){
        console.log('cookies',JSON.stringify(cookies));
        keys = cookies.keys();
      }
    });

    WebApp.connectHandlers.use(cookie.middleware());
    console.log('keys?',keys);

    // ...
  }
});
```

I added a breakpoint and debug prints to check it out, but I'm not seeing anything helpful yet.
![image:200](https://cloud.githubusercontent.com/assets/12083/11547632/74eacc80-9923-11e5-92c6-1708df490386.png)

**Comment by dr-dimitru** [comment]
@roblingle , `WebApp.connectHandlers.use(cookie.middleware());` is server only. Doesn't need to be wrapped to anything.
Just create file in `server` directory with this content:

``` javascript
new Cookies({
  auto: false, // Do not bind middleware by default
  handler: function(cookies){
    console.log('cookies',JSON.stringify(cookies)); // You will have exception here, because `cookies` is not plain object
    keys = cookies.keys();
  }
});

WebApp.connectHandlers.use(cookie.middleware());
```

**Comment by roblingle** [comment]
Well, I see it log an object with TTL, runOnServer, response, cookies, etc on every page load- either using the alternate or typical methods. 

``` javascript
// /server/cookies.js
var cookies = new Cookies();

WebApp.connectHandlers.use(function(req){
    let cookies = req.Cookies;
    console.log(cookies.keys());
});
```

The cookies I want are there but maybe that handler is being run after Iron Router gets the request, because in IR my request has no Cookies property for me to pull from.

**Comment by dr-dimitru** [comment]
Use `WebApp.connectHandlers` instead of IR. And add route handler right after Cookies middleware.

**Comment by dr-dimitru** [comment]
@roblingle or maybe I didn't get what you actually need, can you describe what you need more expressive?

**Comment by roblingle** [comment]
@dr-dimitru It looks like that will work. I'm using IR for my other routes, so I'd prefer to be consistent- in the same way, I like this library because it aims to create a consistent, isomorphic cookies API.

IR makes it easier to pull variables from the URL and has some other conveniences, but currently I'm only trying to handle '/users/export' and send a CSV- no subscriptions to handle, no data to set up, so it's not a big loss to use `WebApp.connectHandlers` instead. :smile: 

I'd assumed that middleware could modify the request (e.g., to add `Cookies` to the request) and that modification would still be present when IR (or FlowRouter, etc.) started handling. That doesn't appear to be the case, although it looks like it did work for @biofractal. Maybe a change in 1.2 prevents that now.

**Comment by roblingle** [comment]
And,  it turned out that all I needed to do was

``` javascript
// /lib/cookies.js
new Cookies();
```

 and now it does modify the requests I see in IR. :blush: Thanks for writing this.

**Comment by dr-dimitru** [comment]
@roblingle glad you find a solution. But I supposed to ask you first about isomorphic driver initialisation.

**Comment by dr-dimitru** [comment]
@roblingle btw if you found this driver useful do not hesitate to star it at both github and atmosphere. Also you may like to [Tweet](https://twitter.com/share?url=https://github.com/VeliovGroup/Meteor-Cookies&text=Easy-peasy%20isomorphic%20boilerplate%20cookies%20for%20Meteor) about it or share at [Facebook](https://www.facebook.com/sharer.php?u=https://github.com/VeliovGroup/Meteor-Cookies)

**Comment by roblingle** [comment]
Done. Thanks again.

**Comment by dr-dimitru** [comment]
Reopen in case someone get into similar issues

**Comment by dr-dimitru** [comment]
Not relative to latest version
