### ISSUE TITLE
Deserialization error help

### ISSUE THREAD

**Issue by carlosalvidrez** [VeliovGroup/Meteor-Cookies#10]
I wonder if there is a bug preventing the cookie saved in UTF-8 encoding from being read.

Getting this error message on startup, when I simply read a cookie saved during the previous session:

VM10497:1 Uncaught SyntaxError: Unexpected token u in JSON at position 1
    at JSON.parse (<anonymous>)
    at deserialize (cookies.js:259)
    at Cookies.get (cookies.js:302)
    at MY_FUNCTION_NAME (MY_FUNCTION_NAME.js:11)
    at My_JS_FILE.js:154

Thanks!

PS. The name of the cookie contains dashes (don't think that's the problem).
PPS. The value of the cookie can begin with an asterisk.

**Comment by dr-dimitru** [comment]
Hello @carlosalvidrez ,

Could you please add exact examples with names and values of cookies?
We need to reproduce it on our end.

**Comment by carlosalvidrez** [comment]
False alarm, sorry. I was wrongly storing a function. My mistake. Thanks!!

**Comment by carlosalvidrez** [comment]
Thanks

**Comment by dr-dimitru** [comment]
@carlosalvidrez I'm glad it's solved 👍
