### ISSUE TITLE
Can't  set a cookie with this value & how to get httpOnly cookie on client after it is set I am getting undefined

### ISSUE THREAD

**Issue by nikhilgoswami** [VeliovGroup/Meteor-Cookies#18]
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiJqVGdONGRHV1duamFaanc2YiIsInVzZXJuYW1lIjoiOTg3MTE2NDQxMSIsInBlcm1pc3Npb25zIjp7ImxpY2Vuc2VkVXNlcnMiOjEwMDAsInRhYnMiOlsicGlnZW9uaG9sZSIsInJlcG9ydHMiLCJhbGxkb2N1bWVudHMiLCJhcHByb3ZhbCIsInByaW50ZWRkb2N1bWVudHMiLCJlaW52b2ljZSIsImNvbnRhY3RsZXNzIiwib3dzdGVzdCIsImxveWFsdHkiLCJkb2NRdWV1ZSJdLCJmb3JtcyI6W10sInNldHRpbmdzIjpbImNhcHRhaW4iLCJnZW5lcmFsIiwidGFibGVCb29raW5nIiwidGVybWluYWxzIiwidGVybXMiLCJkb2NXb3JrZmxvdyIsImVtYWlsIiwicmVwb3J0U2V0dGluZ3MiLCJ1c2VycyIsImdlbmVyaWNGb3JtcyIsImNvbnRhY3RsZXNzIiwiZGlnaXRhbE1lbnUiLCJ0cmFuc2FjdGlvbkNvZGVzIiwiZWludm9pY2UiXSwiZmVlZGJhY2tzIjpbImRhc2hib2FyZCIsImxpc3QiXSwiY29udGFjdHMiOlsiYXBwcm92ZWQiLCJjcmVhdGUiLCJleHBvcnQiLCJpbXBvcnQiLCJwZW5kaW5nIiwic2hvd2FsbCIsInRhZ3MiLCJ1bm1hc2siXSwicmVwb3J0cyI6WyJjaGVja2lucyIsImNoZWNrb3V0cyIsImZuQkNoZWNrVGltZSIsImZvcmV4IiwiZ3Vlc3RCb29raW5ncyIsImluaG91c2VDb21wYXJlIiwicGFpZG91dCIsInBtc0luaG91c2UiLCJyb29tU2V0dGxlbWVudCIsInZvaWREb2N1bWVudHMiLCJmbkJTYWxlcyIsIndvcmtmbG93Iiwic2VudEVtYWlscyIsImZuYkNsb3NlQ2hlY2tPdXRSZXBvcnRzIiwiZm5iQ292ZXJTdGF0ZW1lbnQiLCJmbmJSZXZlbnVlQ2VudGVyRmluYW5jaWFsIiwiZm5iU3lzdGVtRmluYW5jaWFsIiwiZ3Vlc3RMZWRnZXJzIiwidm9pZEl0ZW1zIiwidHJpYWxCYWxhbmNlIiwidHJhbnNhY3Rpb25Kb3VybmFscyIsInJlc2VydmF0aW9uc1RvZGF5IiwicmVzZXJ2YXRpb25DYW5jZWxsYXRpb25zIiwicHJpY2VBbm9tYWx5IiwibGF0ZUNoZWNrT3V0IiwiZm5CU2V0dGxlbWVudCIsImVhcmx5Y2hlY2tpbiIsImRlcGFydHVyZURldGFpbHMiLCJhcnJpdmFsRGV0YWlscyIsImZuYkNhc2hTdW1tYXJ5IiwiZm5iUmV2ZW51ZSIsImZvZG9jdW1lbnRzIiwicG9zY2hlY2tzIiwidXBjb21pbmdBcnJpdmFscyIsImNjQXZlbnVlVHJhbnNhY3Rpb25zUmVwb3J0IiwiY29udGFjdGxlc3NFbWFpbHMiLCJlaW52b2ljZSJdLCJjYXRzIjpbIklOSE9VU0UiLCJSRVNUQVVSQU5UIl0sInByb2ZpbGVNZW51IjpbImdyb3VwQ2hlY2tpbnMiXSwibG95YWx0eSI6WyJhY3RpdmUiLCJjYW5jZWxsZWRNZW1iZXJzaGlwIiwicGVuZGluZ0FwcHJvdmFsIiwicmVqZWN0ZWQiLCJyZW5ld2FsUGVuZGluZyIsInJlcG9ydGNhdGVnb3J5IiwicmVwb3J0bWVtYmVyIiwicmVwb3J0cHJvcGVydHkiLCJ0cmFuc2Zlck1lbWJlciIsIndhdGNoTGlzdEFjY291bnQiXSwiZW5hYmxlRWRjRGV2aWNlIjpmYWxzZSwiY29udGFjdGxlc3MiOnsiZW5hYmxlIjp0cnVlLCJVUkwiOiJodHRwczovL2Rldi5lY29iaWxsei5jb20vcmVtb3RlIiwicGF0dGVybiI6IjYiLCJvcHRpb25zIjpbImZyb250T2ZmaWNlIiwiZm5iIl0sImZuYkxpY2Vuc2VzIjoiIn0sImxveWFsdHlQcm9ncmFtTmFtZSI6IkJlbHZlZGVyZSIsImxveWFsdHlBY2Nlc3MiOlt7InVzZXJUeXBlIjoiZmluYW5jZSIsImZvcm1JZCI6IiJ9LHsidXNlclR5cGUiOiJtYW5hZ2VyIiwiZm9ybUlkIjoiIn0seyJ1c2VyVHlwZSI6Im9wZXJhdGlvbnMiLCJmb3JtSWQiOiIifSx7InVzZXJUeXBlIjoic2FsZXMiLCJmb3JtSWQiOiIifV0sImVuYWJsZU9wZXJhSW50ZWdyYXRpb24iOnRydWV9LCJzY29wZSI6WyJsaWNlbnNlZFVzZXJzIiwidGFicyIsInBpZ2VvbmhvbGUiLCJyZXBvcnRzIiwiYWxsZG9jdW1lbnRzIiwiYXBwcm92YWwiLCJwcmludGVkZG9jdW1lbnRzIiwiZWludm9pY2UiLCJjb250YWN0bGVzcyIsIm93c3Rlc3QiLCJsb3lhbHR5IiwiZG9jUXVldWUiLCJzZXR0aW5ncyIsInNldHRpbmdzLmNhcHRhaW4iLCJzZXR0aW5ncy5nZW5lcmFsIiwic2V0dGluZ3MudGFibGVCb29raW5nIiwic2V0dGluZ3MudGVybWluYWxzIiwic2V0dGluZ3MudGVybXMiLCJzZXR0aW5ncy5kb2NXb3JrZmxvdyIsInNldHRpbmdzLmVtYWlsIiwic2V0dGluZ3MucmVwb3J0U2V0dGluZ3MiLCJzZXR0aW5ncy51c2VycyIsInNldHRpbmdzLmdlbmVyaWNGb3JtcyIsInNldHRpbmdzLmNvbnRhY3RsZXNzIiwic2V0dGluZ3MuZGlnaXRhbE1lbnUiLCJzZXR0aW5ncy50cmFuc2FjdGlvbkNvZGVzIiwic2V0dGluZ3MuZWludm9pY2UiLCJmZWVkYmFja3MiLCJmZWVkYmFja3MuZGFzaGJvYXJkIiwiZmVlZGJhY2tzLmxpc3QiLCJjb250YWN0cyIsImNvbnRhY3RzLmFwcHJvdmVkIiwiY29udGFjdHMuY3JlYXRlIiwiY29udGFjdHMuZXhwb3J0IiwiY29udGFjdHMuaW1wb3J0IiwiY29udGFjdHMucGVuZGluZyIsImNvbnRhY3RzLnNob3dhbGwiLCJjb250YWN0cy50YWdzIiwiY29udGFjdHMudW5tYXNrIiwicmVwb3J0cyIsInJlcG9ydHMuY2hlY2tpbnMiLCJyZXBvcnRzLmNoZWNrb3V0cyIsInJlcG9ydHMuZm5CQ2hlY2tUaW1lIiwicmVwb3J0cy5mb3JleCIsInJlcG9ydHMuZ3Vlc3RCb29raW5ncyIsInJlcG9ydHMuaW5ob3VzZUNvbXBhcmUiLCJyZXBvcnRzLnBhaWRvdXQiLCJyZXBvcnRzLnBtc0luaG91c2UiLCJyZXBvcnRzLnJvb21TZXR0bGVtZW50IiwicmVwb3J0cy52b2lkRG9jdW1lbnRzIiwicmVwb3J0cy5mbkJTYWxlcyIsInJlcG9ydHMud29ya2Zsb3ciLCJyZXBvcnRzLnNlbnRFbWFpbHMiLCJyZXBvcnRzLmZuYkNsb3NlQ2hlY2tPdXRSZXBvcnRzIiwicmVwb3J0cy5mbmJDb3ZlclN0YXRlbWVudCIsInJlcG9ydHMuZm5iUmV2ZW51ZUNlbnRlckZpbmFuY2lhbCIsInJlcG9ydHMuZm5iU3lzdGVtRmluYW5jaWFsIiwicmVwb3J0cy5ndWVzdExlZGdlcnMiLCJyZXBvcnRzLnZvaWRJdGVtcyIsInJlcG9ydHMudHJpYWxCYWxhbmNlIiwicmVwb3J0cy50cmFuc2FjdGlvbkpvdXJuYWxzIiwicmVwb3J0cy5yZXNlcnZhdGlvbnNUb2RheSIsInJlcG9ydHMucmVzZXJ2YXRpb25DYW5jZWxsYXRpb25zIiwicmVwb3J0cy5wcmljZUFub21hbHkiLCJyZXBvcnRzLmxhdGVDaGVja091dCIsInJlcG9ydHMuZm5CU2V0dGxlbWVudCIsInJlcG9ydHMuZWFybHljaGVja2luIiwicmVwb3J0cy5kZXBhcnR1cmVEZXRhaWxzIiwicmVwb3J0cy5hcnJpdmFsRGV0YWlscyIsInJlcG9ydHMuZm5iQ2FzaFN1bW1hcnkiLCJyZXBvcnRzLmZuYlJldmVudWUiLCJyZXBvcnRzLmZvZG9jdW1lbnRzIiwicmVwb3J0cy5wb3NjaGVja3MiLCJyZXBvcnRzLnVwY29taW5nQXJyaXZhbHMiLCJyZXBvcnRzLmNjQXZlbnVlVHJhbnNhY3Rpb25zUmVwb3J0IiwicmVwb3J0cy5jb250YWN0bGVzc0VtYWlscyIsInJlcG9ydHMuZWludm9pY2UiLCJjYXRzIiwiY2F0cy5JTkhPVVNFIiwiY2F0cy5SRVNUQVVSQU5UIiwicHJvZmlsZU1lbnUiLCJwcm9maWxlTWVudS5ncm91cENoZWNraW5zIiwibG95YWx0eSIsImxveWFsdHkuYWN0aXZlIiwibG95YWx0eS5jYW5jZWxsZWRNZW1iZXJzaGlwIiwibG95YWx0eS5wZW5kaW5nQXBwcm92YWwiLCJsb3lhbHR5LnJlamVjdGVkIiwibG95YWx0eS5yZW5ld2FsUGVuZGluZyIsImxveWFsdHkucmVwb3J0Y2F0ZWdvcnkiLCJsb3lhbHR5LnJlcG9ydG1lbWJlciIsImxveWFsdHkucmVwb3J0cHJvcGVydHkiLCJsb3lhbHR5LnRyYW5zZmVyTWVtYmVyIiwibG95YWx0eS53YXRjaExpc3RBY2NvdW50IiwiZW5hYmxlRWRjRGV2aWNlIiwiY29udGFjdGxlc3MiLCJsb3lhbHR5UHJvZ3JhbU5hbWUiLCJsb3lhbHR5QWNjZXNzIiwibG95YWx0eUFjY2Vzcy5bb2JqZWN0IE9iamVjdF0iLCJsb3lhbHR5QWNjZXNzLltvYmplY3QgT2JqZWN0XSIsImxveWFsdHlBY2Nlc3MuW29iamVjdCBPYmplY3RdIiwibG95YWx0eUFjY2Vzcy5bb2JqZWN0IE9iamVjdF0iLCJlbmFibGVPcGVyYUludGVncmF0aW9uIiwib3duX3Byb2ZpbGUiLCJvdXRsZXRzIl0sIm1lcmNoYW50VXNlcklkIjpudWxsLCJ1c2VyVHlwZUlkIjoiIiwibWVyY2hhbnRJZCI6IjdiMTMzMzdhN2UwOGI5NTFhOTJkODdjNSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTYwMzI3ODMxNSwiZXhwIjoxNjAzMjgxOTE1fQ.gc07rBkWu0tcEeJzUsKkL3AZWFYZU6f-cwaF-vGXjP4

**Comment by dr-dimitru** [comment]
Hey @nikhilgoswami,

Wow! What's up with this message?

About `httpOnly`, well... it is a feature, such cookie __does not__ available on the *Client*

**Comment by nikhilgoswami** [comment]
Thanks I think answer for first question is size of string is more than 4k bytes allowed by most browsers

**Comment by dr-dimitru** [comment]
@nikhilgoswami I'm glad it's solved now 👍

Please support this project with:
 - [Become a sponsor on GitHub](https://github.com/sponsors/dr-dimitru/dashboard) and GitHub __would double your every contribution__ in next 12 months!;
 - Support [via PayPal](https://paypal.me/veliovgroup);
 - Star this package on GitHub;
 - Like [at Facebook](https://www.facebook.com/veliovgroup);
 - Follow [on Twitter](https://twitter.com/veliovgroup);
 - Check and star our [other open source projects on GitHub](https://github.com/VeliovGroup).
