### ISSUE TITLE
cookies.get fails with exception

### ISSUE THREAD

**Issue by bladerunner2020** [VeliovGroup/Meteor-Cookies#19]
I save in cookies the search string. If the saved string is "Device undefined (" the get method fails with an exception in JSON.parse.

It happened in ` return JSON.parse(string);` line in this part of code:
```js
const isStringifiedRegEx = /JSON\.parse\((.*)\)/;
const isTypedRegEx = /false|true|null|undefined/;
const deserialize = (string) => {
  if (typeof string !== 'string') {
    return string;
  }

  if (isStringifiedRegEx.test(string)) {
    let obj = string.match(isStringifiedRegEx)[1];
    if (obj) {
      try {
        return JSON.parse(decode(obj));
      } catch (e) {
        console.error('[ostrio:cookies] [.get()] [deserialize()] Exception:', e, string, obj);
        return string;
      }
    }
    return string;
  } else if (isTypedRegEx.test(string)) {
    return JSON.parse(string);
  }
  return string;
};
```
Should  `const isTypedRegEx = /false|true|null|undefined/;` replaced with `const isTypedRegEx = /^(false|true|null|undefined)$/;`?
And 'undefined is not a valid string for parsing...

**Comment by dr-dimitru** [comment]
Feel free to reopen it in case if the issue is still persists on your end.
