### ISSUE TITLE
Doesn't seem to work with METEOR@1.1.0.3 release

### ISSUE THREAD

**Issue by wizonesolutions** [VeliovGroup/Meteor-Cookies#4]
I get an empty object in `Package["ostrio:cookies"]` and `Cookies` is not exported to the global namespace. I've checked on both client and server.

**Comment by wizonesolutions** [comment]
By comparison, https://atmospherejs.com/storeness/cookie does work for some reason. Hope that helps.

**Comment by dr-dimitru** [comment]
Have you run tests over this package?:

``` shell
git clone  https://github.com/VeliovGroup/Meteor-Cookies.git
cd Meteor-Cookies
meteor test-packages ./
```
1. Have you read [this thread](https://github.com/VeliovGroup/Meteor-Cookies/issues/1)?
2. How do you include this package into your app?
3. How do you use this package in you app? Could you provide code blocks where you use it?

_We're using this package daily, including latest Meteor release and everything is working properly on our end_.

**Comment by wizonesolutions** [comment]
@dr-dimitru thee problem perhaps is that the `versionsFrom` stanza in `package.js` is too old for how the package actually works? Try adding it to a Meteor demo app specifically witgh

**Comment by wizonesolutions** [comment]
@dr-dimitru thee problem perhaps is that the `versionsFrom` stanza in `package.js` is too old for how the package actually works? Try adding it to a Meteor demo app specifically with `--release METEOR@1.1.0.3` and see if you can access its namespace. If so, it is app-specific for me then and you can close this issue :)

**Comment by dr-dimitru** [comment]
Should work properly since 1.0. Does tests fails on your meteor release?

**Comment by dr-dimitru** [comment]
``` shell
meteor test-packages ./ --release METEOR@1.1.0.3
```

all tests successfully passed, so it's on your end

**Comment by dr-dimitru** [comment]
@wizonesolutions any news on your end?

**Comment by wizonesolutions** [comment]
The other package we went with worked fine, so I'm probably never going to check this. I suspect that the tests passed because they are run in a package context, not in an app context (the problem was when the app tried to use a global). But I don't want to clog up your issue list.
