### ISSUE TITLE
Bug with Infinity

### ISSUE THREAD

**Issue by fgro93** [VeliovGroup/Meteor-Cookies#5]
https://github.com/VeliovGroup/Meteor-Cookies/blob/master/cookies.coffee#L125

instead of `pair.` this should be `pairs.`

**Comment by dr-dimitru** [comment]
@fgro93 good catch
Would you like to send a PR? Or I'll do it myself

**Comment by fgro93** [comment]
@dr-dimitru It is such a small fix, please do it yourself. Thanks!

**Comment by dr-dimitru** [comment]
@fgro93 thank you for reporting this.

Please support this project by:
- Star on [GitHub](https://github.com/VeliovGroup/Meteor-Cookies)
- Star on [Atmosphere](https://atmospherejs.com/ostrio/cookies)
