### ISSUE TITLE
Empty value causes exception 

### ISSUE THREAD

**Issue by dr-dimitru** [VeliovGroup/Meteor-Cookies#6]
See - https://github.com/VeliovGroup/Meteor-Files/issues/327
Thanks to @derwok

@derwok Could you please run build-in tests on IE?

**Comment by derwok** [comment]
Hi @dr-dimitru ,
I just noticed - there is an action item for me here.
I would really like to help here - as this one VeliovGroup/Meteor-Files#327 really bugs us.

Could you just give me some more hints, of the execute the cookie tests inside IE11 browser?

WOK.

**Comment by dr-dimitru** [comment]
Hello @derwok ,

No worries, going to fix this one then put my hands to update Meteor-Files package

**Comment by dr-dimitru** [comment]
Hello @derwok ,

This should be fixed in [`v2.1.0`](https://github.com/VeliovGroup/Meteor-Cookies/releases/tag/2.1.0)
Going to proceed to https://github.com/VeliovGroup/Meteor-Files/issues/327

Let me know if you will have a chance to test this package with Meteor-Files as local dependency

**Comment by dr-dimitru** [comment]
Looks like it was fixed.
Feel free to reopen it.
