### ISSUE TITLE
How to delete cookies

### ISSUE THREAD

**Issue by prachi0708** [VeliovGroup/Meteor-Cookies#7]
I am able to create cookies by using this package in meteor.
But I am not able to expire cookies after 30 seconds.
So, please tell what is the command to expire cookies and how to use it

**Comment by dr-dimitru** [comment]
Hello @prachi0708 ,

[`.remove(key)`](https://github.com/VeliovGroup/Meteor-Cookies#cookiesremovekey-path-domain-isomorphic) method doesn't work well?

Could you post how cookie is set?

**Comment by prachi0708** [comment]
I don't want to delete cookies after some event.
I want to delete cookies if user don't perform operation on site for 30 seconds.
after 30 second of inactivity cookies should be deleted.

I am setting cookies like this:  cookies.set('locale', 'en'); 
on client side

**Comment by dr-dimitru** [comment]
Well, you should use timers as `expires` or `maxAge` flags will expire cookie anyways.

```js
cookies.set('key', 'val');
const timer = Meteor.setTimeout(() => {
  cookies.remove('key');
}, 30000);

const functionWhichIndicatesUsersActivity = () => {
  Meteor.clearTimeout(timer);
};
```

**Comment by prachi0708** [comment]
I have 1 more doubt if we are using remove for setting time of expiration, then what is the use of opts.TTL and opts.expires

i.e. How we can use expire. I am unable to expire cookies using expires

**Comment by dr-dimitru** [comment]
`TTL` is instance-wide defaults of [`max-age`](https://en.wikipedia.org/wiki/HTTP_cookie#Expires_and_Max-Age), and by default it equals to *Session*.

To make *almost* infinite `max-age` set it to `2147483647`

__OR:__

Use `expires` option when you set cookie:

```js
cookies.set('key', 'val', {expires: Infinity});
```

**Comment by dr-dimitru** [comment]
@prachi0708 ,

May be this lib - [Client Storage](https://github.com/VeliovGroup/Client-Storage) will be a better fit for your needs? As it will work even if cookies is disabled, or user in private mode.

**Comment by prachi0708** [comment]
I am using it like this:
 var date = new Date();
 date.setTime(date.getTime() + (5 * 1000));
 cookies.set("example", "foo", { expires: date });

But it is not working for me.

**Comment by dr-dimitru** [comment]
```js
cookies.set("example", "foo", { expires: new Date(+new Date() + 50000) });
// 50000 is 50 sec
// Earlier you mentioned "..expire cookies after 30 seconds.."
// So, it should be 30000
```

> But it is not working for me.

What browser inspector says?

**Comment by prachi0708** [comment]
yes, but cookie is not removing even after 1 minute.

I tried above code also it is also not working.

In brower inspector when i run cookies.cookies it still show cookie there.

**Comment by dr-dimitru** [comment]
(Chrome/Opera) Inspector -> Application -> Cookies

And, yes, cookie will exists anyways unless page is reloaded.
I really believe you have chosen not the best tool (cookies) to solve your task.

Could you describe more widely what you're trying to implement?

**Comment by prachi0708** [comment]
yes, cookies get deleted from there ( Inspector -> Application -> Cookies).
I don't know about refreshing page for deleting cookies.
I do think now tool will solve my problem. Will tell after implementing.

**Comment by dr-dimitru** [comment]
1. What browser you're on?
 2. You've mentioned - `I want to delete cookies if user don't perform operation on site for 30 seconds.`, `expires` or `maxAge` will remove cookie anyways, without dependence of users actions. Or you overwrite cookie with new `expires` flag on every user action?

**Comment by dr-dimitru** [comment]
Closed due to silence at issue owner end.
Feel free to reopen it in case if the issue still persists on your end.
