### ISSUE TITLE
IE 10 and IE 11 - Error - Invalid Calling Object

### ISSUE THREAD

**Issue by muksyd** [VeliovGroup/Meteor-Cookies#8]
### I'm having an issue:
  - All IE 10 and 11 users are exepriencing the following error on the compiled code
Invalid Calling Object - line 25 of cookies.js
  - Latest version of `ostrio:cookies` 
  - Meteor 1.7.0.3
  - Client Issue
  - IE 10 and IE 11 - Some Edge browsers
  - Screenshot - https://www.dropbox.com/s/fd2bp9aal02wsh8/Screenshot%202018-07-04%2012.46.15.png?dl=0

### I have a suggestion:
Change **_line 25_** cookies.js to
 `const toString = Object.prototype.toString;`
`return toString.call(obj) == '[object ' + _helpers[i] + ']';`

**Comment by dr-dimitru** [comment]
@schryised good catch, going to release a fix, thank you.

**Comment by dr-dimitru** [comment]
@schryised thank you for contribution.
Released as [`v2.2.7`](https://github.com/VeliovGroup/Meteor-Cookies/releases/tag/2.2.7)
Let me know if issue is fixed at your end.

**Comment by muksyd** [comment]
@dr-dimitru thank you for the quick response and release. It is always a pleasure using your packages!! Appreciate it.

**Comment by dr-dimitru** [comment]
@schryised thank you for contribution and support.

Please, support this project by:
 - Star on [GitHub](https://github.com/VeliovGroup/Meteor-Cookies)
 - Star on [Atmosphere](https://atmospherejs.com/ostrio/cookies)
 - Check [other packages](https://github.com/search?o=desc&q=topic%3Ameteor-package+org%3AVeliovGroup&s=stars&type=Repositories) we have made
 - Share on [Facebook](https://www.facebook.com/sharer.php?u=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Cookies) and [Twitter](https://twitter.com/share?url=https%3A%2F%2Fgithub.com%2FVeliovGroup%2FMeteor-Cookies)
 - [Donate via PayPal](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=FVDSXRFW9VGA2)
